/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        background: '#faf9f8',
        error: '#9e422c',
        'error-container': '#fe8b70',
        'error-dim': '#5c1202',
        'inverse-on-surface': '#9d9d9c',
        'inverse-primary': '#ddfef4',
        'inverse-surface': '#0d0e0e',
        'on-background': '#2f3333',
        'on-error': '#fff7f6',
        'on-error-container': '#742410',
        'on-primary': '#defff5',
        'on-primary-container': '#3a5750',
        'on-primary-fixed': '#28453e',
        'on-primary-fixed-variant': '#44615a',
        'on-secondary': '#e7fef6',
        'on-secondary-container': '#415650',
        'on-secondary-fixed': '#2f433e',
        'on-secondary-fixed-variant': '#4b605a',
        'on-surface': '#2f3333',
        'on-surface-variant': '#5b605f',
        'on-tertiary': '#f2fcf2',
        'on-tertiary-container': '#545e57',
        'on-tertiary-fixed': '#424c45',
        'on-tertiary-fixed-variant': '#5f6861',
        outline: '#777c7b',
        'outline-variant': '#aeb3b2',
        primary: '#47645d',
        'primary-container': '#c9e9e0',
        'primary-dim': '#3b5851',
        'primary-fixed': '#c9e9e0',
        'primary-fixed-dim': '#bbdbd2',
        secondary: '#4f635d',
        'secondary-container': '#d1e8e0',
        'secondary-dim': '#435751',
        'secondary-fixed': '#d1e8e0',
        'secondary-fixed-dim': '#c3d9d2',
        surface: '#faf9f8',
        'surface-bright': '#faf9f8',
        'surface-container': '#edeeed',
        'surface-container-high': '#e6e9e8',
        'surface-container-highest': '#dfe3e2',
        'surface-container-low': '#f3f4f3',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#d6dbda',
        'surface-tint': '#47645d',
        'surface-variant': '#dfe3e2',
        tertiary: '#58615a',
        'tertiary-container': '#ecf6ed',
        'tertiary-dim': '#4c554f',
        'tertiary-fixed': '#ecf6ed',
        'tertiary-fixed-dim': '#dee8df',

        // Legacy mappings for existing components to not break
        'bg-primary': '#faf9f8',
        'bg-secondary': '#f3f4f3',
        'bg-card': '#ffffff',
        'bg-hover': '#edeeed',
        'bg-input': '#ffffff',
        'accent': '#47645d',
        'accent-soft': '#c9e9e0',
        'accent-dim': '#3b5851',
        'accent-faint': 'rgba(71, 100, 93, 0.08)',
        'accent-glow': 'rgba(71, 100, 93, 0.15)',
        'text-primary': '#2f3333',
        'text-secondary': '#5b605f',
        'text-muted': '#777c7b',
        'text-hint': '#aeb3b2',
        'border': '#e6e9e8',
        'border-mid': '#dfe3e2',
        'border-light': '#edeeed',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Fira Code', 'Courier New', 'monospace'],
      },
      borderRadius: {
        'md': '0.75rem',
        'xl': '1.5rem',
        'full': '9999px'
      },
      animation: {
        'fade-up': 'fadeUp 0.22s ease both',
        'blink': 'blink 1s step-end infinite',
        'pulse-dot': 'pulseDot 2s ease-in-out infinite',
        'typing': 'typing 1.2s infinite',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(6px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        blink: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        pulseDot: {
          '0%, 100%': { opacity: '1', transform: 'scale(1)' },
          '50%': { opacity: '0.4', transform: 'scale(0.75)' },
        },
        typing: {
          '0%, 60%, 100%': { opacity: '0.2', transform: 'translateY(0)' },
          '30%': { opacity: '1', transform: 'translateY(-4px)' },
        },
      },
      boxShadow: {
        'ambient': '0px 12px 32px rgba(47, 51, 51, 0.06)'
      }
    },
  },
  plugins: [],
};
